### ISSUE TITLE
Direwolf support for CM108 Audio Adapter

### ISSUE THREAD

**Issue by b33ngaming** [km4ack/pi-build#103]
Hi Jason, I love the build a pi script, 

I would like to suggest adding the support for the CM108 adapters as described in section 5.2.4 of the [Direwolf User Guide](https://github.com/wb2osz/direwolf/blob/master/doc/User-Guide.pdf) to your build a pi script.  Is it possible for the script to download and install libudev-dev before compiling and installing direwolf?  I personally have a [RA-35](http://www.masterscommunications.com/products/radio-adapter/ra35.html) USB audio adapter, and editing line 195 in direwolf.conf to PTT CM108 gives the error in the attached picture.

Thank you for taking the time, and this is a great thing you've put together!

![image](https://user-images.githubusercontent.com/68155527/87865309-a0706880-c941-11ea-9d25-af03207f3698.png)

**Comment by b33ngaming** [comment]
I failed to mention that this isn't a blocker.  Installing the package and running Build a Pi again for Direwolf took care of it.  Everything is working as I hoped it would.

**Comment by km4ack** [comment]
Just to make sure I understand correctly, you ran Build a Pi again and that solved the problem?

73, de KM4ACK

**Comment by b33ngaming** [comment]
Yes sir, I installed libudev-dev with `sudo apt install libudev-dev` and then ran build a pi again, only selecting Direwolf.  Direwolf checks for the package and then configures it when compiling I guess.  :)

Thanks for your time!
