### ISSUE TITLE
Conky doesn't display nice cyrillic.

### ISSUE THREAD

**Issue by dafula** [km4ack/pi-build#105]
Hi!
I have troubles when using cyrillic (locale set to country with Cyrillic alphabet). The date is showed in locale's format and it's unreadable on the screen.
I found a simple solution - a small change in the config file:

**override_utf8_locale no**

should become

**override_utf8_locale yes**

Also it's better to migrate the config file in the new conky format, which can be seen at https://github.com/brndnmtthws/conky/wiki/Configurations
I have made the needed changes in .conkyrc, conky-small, conky-medium and conky-large files.
I attach the new files if Jason KM4ACK decides to put them in the repository.

Before:
![conky_before](https://user-images.githubusercontent.com/23299264/88102358-170e9f80-cba8-11ea-990b-fa1fdbe203a9.jpg)

After:
![conky_after](https://user-images.githubusercontent.com/23299264/88102354-16760900-cba8-11ea-83ec-f29850e80574.jpg)

The updated files - added .txt for the upload here:

[conky-large.txt](https://github.com/km4ack/pi-build/files/4956000/conky-large.txt)
[conky-medium.txt](https://github.com/km4ack/pi-build/files/4956001/conky-medium.txt)
[conky-small.txt](https://github.com/km4ack/pi-build/files/4956002/conky-small.txt)
[dot_conkyrc.txt](https://github.com/km4ack/pi-build/files/4956003/dot_conkyrc.txt)

73!
LZ1DAF

**Comment by km4ack** [comment]
THANKS!!

**Comment by km4ack** [comment]
Slated for 3.0.5. In dev branch now.
