### ISSUE TITLE
Chirp not updating to latest version

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#107]

**Comment by km4ack** [comment]
this issue based on this post https://groups.io/g/KM4ACK-Pi/topic/chirp_not_updating_bap_3_0_2/75751539?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,75751539

I am unable to duplicate the issue on 2 different systems. one pi 3 and the other a pi 4

**Comment by Jeepien** [comment]
I've confirmed that the problem exists on my Pi 4.

**Comment by km4ack** [comment]
duplicate issue that will be resolved in 3.0.3 https://github.com/km4ack/pi-build/issues/108

as a temp fix, run:
rm -rf ~/pi-build/temp/*
and try the update again from the BAP update script in the main menu.

73, de KM4ACK
