### ISSUE TITLE
FEATURE REQUEST - gpredict

### ISSUE THREAD

**Issue by mattybaus** [km4ack/pi-build#110]
Hi

It would be nice if gpredict or another satellite/rotator control was added to the suite.

73

Matt
9V1MH

**Comment by km4ack** [comment]
gpredict is in 3.0.3 beta. See this post if you want to try the beta https://groups.io/g/KM4ACK-Pi/topic/build_a_pi_v3_0_3_beta/75929411?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,75929411
