### ISSUE TITLE
Gridsquare does not display

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/pi-build#116]
I just upgraded to BAP 3.0.3 as it was offered when I ran Preferences > Build-a-Pi
I installed GPS as I expected that would be a feature of this version that would support my BU-353S4 GPS.
When I rebooted, Conky does not show my Gridsquare.
I ran cgps and it shows that the GPS is recognized, and shows my gridsquare among other information.
Did I misunderstand that this release was to support GPS and display gridsquare?

**Comment by km4ack** [comment]
Issue resolved after reinstall of BAP.
