### ISSUE TITLE
GPS GNSS Usb Dongle

### ISSUE THREAD

**Issue by catalinalb** [km4ack/pi-build#123]
Hi,

I have the script installed on the raspberry pi image from https://www.sdrplay.com/raspberry-pi-images/  version V 0,6. 
I did managed somehow to get the GPS GNSS donlge (Bus 001 Device 005: ID 1546:01a8 U-Blox AG [u-blox 8]) 
https://www.amazon.de/gp/product/B07SMRXSC8/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
using the following instructions:

_GPS for Raspberry pi
lsusb
sudo apt -y install gpsd gpsd-clients python-gps 
sudo nano /etc/default/gpsd
#Add this to file
START_DAEMON=”true”
USBAUTO=”true”
DEVICES=”/dev/ttyACM0″
GPSD_OPTIONS=”-n”
save & exit
sudo apt-get install chrony
#check to see if services are running
systemctl is-active gpsd
systemctl is-active chronyd
#Check GPS output
cgps – s
gpsmon -n

#Edit chrony config file
sudo nano /etc/chrony/chrony.conf

#Add this to end of file
refclock SHM 0 offset 0.5 delay 0.2 refid NMEA

#Check Chrony Output
sudo chronyc sources -v

# Check chrony output
sudo chronyc tracking

#Force time sync
sudo chronyc makestep

if still not working:
dmesg | grep -i tty
sudo cat /dev/ttyACM0
sudo gpsd /dev/ttyACM0 -F /var/run/gpsd.sock
cgps -s_

The Problem is that with the SDR device RSP1a plugged in it dose not work. It seems to start working once I unplugged it becasue Conky was showing the gridsqare but then it showed NO GPS.

Please add the suport for the new dongle and tell me if I did something wrong or if there is something else that I should do in order to have it running mostly for time sincronization.

Thank you and 73!,
Catalin,
DE1CTL

**Comment by km4ack** [comment]
support for more GPS units included in v3.0.4
