### ISSUE TITLE
Consider Pactor and IC-M710

### ISSUE THREAD

**Issue by bm31416** [km4ack/pi-build#126]
Being a sailor I would like to be able to operate my IC-M710 with Build a pi (flrig)
and to use  winlink through Pactor (pactor modem SCS PTC IIe or Pmon )
Many sailors still use this combination and would be delighted to use it with Build a Pi.
73 de F4INC

**Comment by km4ack** [comment]
I believe that Pat supports Pactor but you will have to check their forum to be certain. https://groups.google.com/g/pat-users
If so, everything you need should already be in build a pi.
