### ISSUE TITLE
XGPS or similar?

### ISSUE THREAD

**Issue by hicksdp** [km4ack/pi-build#128]
In your video about diagnosing the GPS issue on Field Day, you showed XGPS as a means to see satellite status.  Can you add XGPS or something similar to the next build?  Having the Grid Square display in Conky is nice, but sometimes I'd like to see the GPS coordinates.  Thanks, N4DPH

**Comment by km4ack** [comment]
If you install the GPS software with BAP, xgps is there for your use. Start it from the command line with "xgps"

**Comment by hicksdp** [comment]
Thanks-  XGPS appears, but the fields are blank (even though Conky is showing my grid square).  Also, the window runs off the bottom of the screen and won't resize.

**Comment by km4ack** [comment]
Interesting. Usually it's the other way around. Do you have data with "cgps"?

**Comment by hicksdp** [comment]
No data with cgps either.

David Hicks (256) 565-4020
Sent from my phone

On Sep 8, 2020, at 07:31, KM4ACK <notifications@github.com> wrote:

﻿

Interesting. Usually it's the other way around. Do you have data with "cgps"?

**Comment by km4ack** [comment]
Run this command and post the results please
cat /dev/default/gpsd

**Comment by hicksdp** [comment]
Sorry for the confusion. Another reboot solved the problem. Now a god and cgps are delivering data.

David Hicks (256) 565-4020
Sent from my phone

On Sep 8, 2020, at 07:49, KM4ACK <notifications@github.com> wrote:

﻿

Run this command and post the results please
cat /dev/default/gpsd

**Comment by km4ack** [comment]
Thanks for the update.
