### ISSUE TITLE
Grid Tracker

### ISSUE THREAD

**Issue by robvdveeke** [km4ack/pi-build#130]
There is a new version off Grid Tracker
When I want to install it with build a pi you get an error 
it is missing a file gridtracker.new 
and gives an error installation stopped

**Comment by km4ack** [comment]
Issue resolved in 3.0.4 beta. https://groups.io/g/KM4ACK-Pi/topic/build_a_pi_3_0_4_beta_release/76733597?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76733597
