### ISSUE TITLE
Problem with flrig 

### ISSUE THREAD

**Issue by KM6TAU** [km4ack/pi-build#138]
old version works new one doesnt is there a way to get back to the old version? The earlier version of build a pi worked but V3 wont with my radio anyway G90 with IC7100 What should I do is there a fix I cant be the only one with this problem.
I get com port error and cant connect to the radio cat control

Thanks
Bill

**Comment by km4ack** [comment]
This would be a question for the FLDIGI team https://groups.io/g/linuxham/topics

**Comment by KM6TAU** [comment]
Not sure what happened it seems to be working ok now after another start
over download. And i have started backing up more often after ordering the
sd smart card reader and some new sd cards
