### ISSUE TITLE
GridTracker fails to update

### ISSUE THREAD

**Issue by kirovoleg** [km4ack/pi-build#145]
While trying to update gridtracker via the build-a-pi script the following error appears:

Building dependency tree       
Reading state information... Done
libgconf-2-4 is already the newest version (3.2.6-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2020-09-21 17:43:19--  http://%3Cp/
Resolving <p (<p)... failed: Name or service not known.
wget: unable to resolve host address ‘<p’
--2020-09-21 17:43:19--  ftp://style=%22padding-left/
           => ‘.listing’
Resolving style="padding-left (style="padding-left)... failed: Name or service not known.
wget: unable to resolve host address ‘style="padding-left’
--2020-09-21 17:43:19--  http://40px;%22%3E%3Ca/
Resolving 40px;"><a (40px;"><a)... failed: Name or service not known.
wget: unable to resolve host address ‘40px;"><a’
href="https://www.dropbox.com/s/cin4zacx02owiry/GridTracker-Linux-Arm-1.20.0906.tar.gz: Scheme missing.
tar (child): GridTracker-Linux-Arm-1.20.0906.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove '*.gz': No such file or directory

Checking the code I see that the parameters for getting the URL are the following:

curl -s https://tagloomis.com/downloads/ | grep Arm | head -1 | sed 's/<p><a\ href="//' | sed 's/?.*$//'

but trying that on a console it gets some html code ahead of the url:

pi@raspberrypi3-gps:~ $ curl -s https://tagloomis.com/downloads/ | grep Arm | head -1 | sed 's/<p><a\ href="//' | sed 's/?.*$//'
<p style="padding-left: 40px;"><a href="https://www.dropbox.com/s/cin4zacx02owiry/GridTracker-Linux-Arm-1.20.0906.tar.gz

It seems the web changed so the sed no longer works.

Perhaps replacing the sed so it uses a wildcard before href could be the answer. For example:

curl -s https://tagloomis.com/downloads/ | grep Arm | head -1 | sed 's/^.*href="//' | sed 's/?.*$//'

It seems to work in my setup:

pi@raspberrypi3-gps:~ $ curl -s https://tagloomis.com/downloads/ | grep Arm | head -1 | sed 's/^.*href="//' | sed 's/?.*$//'
https://www.dropbox.com/s/cin4zacx02owiry/GridTracker-Linux-Arm-1.20.0906.tar.gz

**Comment by km4ack** [comment]
This has been addressed in the latest beta build https://groups.io/g/KM4ACK-Pi/topic/build_a_pi_3_0_4_beta_release/76733597?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76733597
