### ISSUE TITLE
rubygems.org and jtdx.tech errors

### ISSUE THREAD

**Issue by mndmr** [km4ack/pi-build#150]
Some errors I noticed while running the script. maybe a change in their path? Built the pi twice on different days. There were others from rubgems but was unable to capture that they were.

ERROR:  Could not find a valid gem 'gpsd_client' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'maidenhead' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
chmod: cannot access '/home/pi/bin/conky/temp-conv': No such file or directory
--2020-09-26 08:26:38--  https://www.jtdx.tech/downloads/Linux/jtdx-2.2.0-rc152_u_armhf.deb
Resolving www.jtdx.tech (www.jtdx.tech)... 2606:4700:3036::6818:6ac9, 2606:4700:3033::ac43:ac69, 2606:4700:3033::6818:6bc9, ...
Connecting to www.jtdx.tech (www.jtdx.tech)|2606:4700:3036::6818:6ac9|:443... failed: Connection timed out.
Connecting to www.jtdx.tech (www.jtdx.tech)|2606:4700:3033::ac43:ac69|:443... failed: Connection timed out.
Connecting to www.jtdx.tech (www.jtdx.tech)|2606:4700:3033::6818:6bc9|:443... failed: Connection timed out.

**Comment by km4ack** [comment]
see issue #153 

https://github.com/km4ack/pi-build/issues/153
