### ISSUE TITLE
No Gridsquare or time update with connected GPS in Conky

### ISSUE THREAD

**Issue by b33ngaming** [km4ack/pi-build#159]
I did a fresh install of Raspbian OS, and Build-a-Pi and conky no longer updates the gridsquare after GPS is locked.  I tried disconnecting from my home internet and powering off the pi for a little while.  When it boots, the time is off as to be expected, but after I get my GPS lock (LED on the dongle) the time doesn't update like it did.

I checked my Build-a-Pi version today, it is at 3.04, and I typed conky into the terminal, and I get the error shown in the screenshot, could be the issue, but I am not that versed in the workings of this software.  I used gpspipe -w in the terminal, and I can see my lat/long output, and elevation, so I believe the data is being streamed to the Pi.

<img width="870" alt="Conky GPS and Time" src="https://user-images.githubusercontent.com/68155527/95788306-49143700-0ca9-11eb-9a61-938394244b37.png">

**Comment by km4ack** [comment]
If you run "cgps" do you have GPS data in the app?

**Comment by b33ngaming** [comment]
Yes sir, as well as xgps, that shows ~10 GPS satellites.

<img width="1080" alt="XGPS and CGPS output" src="https://user-images.githubusercontent.com/68155527/95795280-fa21ce00-0cb7-11eb-88e1-e6f9a9cb3690.png">

**Comment by b33ngaming** [comment]
Not sure if this is a helpful observation, but, usually in the older version of build a pi, I was able to plug the GPS is while the Pi was already booted, and it would work.  This time, I had the Pi off, and didn't have the GPS plugged in when I booted.  The green LED was blinking showing connection, but no data in xgps/cgps.  I had to reboot the Pi, with the GPS Dongle plugged in, and that allowed the data to stream finally.

**Comment by km4ack** [comment]
It is designed so that the GPS has to be plugged in at boot. The GPS is can't be hot swapped. 

It looks like one of the ruby gems didn't install during the build. Install it manually with 
`sudo gem install gpsd_client`

See if conky will give you the gridsquare. You might have to reboot after installing.

**Comment by b33ngaming** [comment]
I did another full install, and a fresh build a pi, no dice still.  I installed gpsd_client, didn't work after the reboot.  I had to install maidenhead, that was the next error after entering `conky` in the terminal.

I have a grid square now, I will try and see if the time updates with GPS tomorrow morning.

**Comment by b33ngaming** [comment]
gpsd_client and maidenhead installs fixed my issue.  Just tested the update of system time, and it worked once the GPS locks.

Thanks for your help.

**Comment by km4ack** [comment]
Glad that fixed it.
