### ISSUE TITLE
BAP and RigPi

### ISSUE THREAD

**Issue by RAbagnale** [km4ack/pi-build#162]
Hi everybody,

I downloaded RigPi and flashed it onto a SD. After starting I installed BAP over it. 
Now there are two issues:
1. RigPi works as a Chromium app and reacts at 127.0.0.1. After installing the emergency email server, this IP directs to it and RigPi doesn't work anymore.
2. RigPi uses Hamlib. Therein I can select my FTdx101d. With BAP I also installed cqrlog which uses Hamlib as well. But my rig is not shown in the list of selectable rigs.

I will open an issue ticket for that as well...

73 de Rico, DG5BQ

**Comment by km4ack** [comment]
You will not be able to install the EES on top of rigpi and have access to rigpi unless you can move it to a different port. The EES is designed to take over the default port 80 on the web server. Avoid installing the EES and you should be ok. 

You second issue would be with CQRlog. I would open an issue ticket there and see if they can help you resolve.
