### ISSUE TITLE
GPS Not Working

### ISSUE THREAD

**Issue by andjones132** [km4ack/pi-build#164]
[GPS_Info.txt](https://github.com/km4ack/pi-build/files/5461582/GPS_Info.txt)

km4ack.

Hi. Thank you for pulling together a fantastic tool for the ham radio community. I have installed the pi build on my Raspberry 4 and everything seems to be working. That is except for my GPS. In the attached txt file you can see that the U-Blox GPS dongle has been recognized ad appears to be on port /dev/ttyACM0. If I run cat /dev/ttyACM0 on this port I get GPS data from the U-Blox dongle. However, cgps or xgsp both show no data. 

I checked the /etc/default/gpsd file and everything appears to be correct. 

```
pi@pibuild:/etc/default $ cat gpsd
#The -b switch was added per https://github.com/km4ack/pi-build/issues/144
#km4ack 24SEPT2020

# Default settings for the gpsd init script and the hotplug wrapper.

# Start the gpsd daemon automatically at boot time
START_DAEMON="true"

# Use USB hotplugging to add new USB devices automatically to the daemon
USBAUTO="false"

# Devices gpsd should collect to at boot time.
# They need to be read/writeable, either by user gpsd or the group dialout.
DEVICES="/dev/ttyACM0"

# Other options you want to pass to gpsd
GPSD_OPTIONS="-n -b"
```
Any ideas what I can try to get this working?

This is the dongle that I am using: https://smile.amazon.com/gp/product/B01MTU9KTF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Update: Even thou when I run cat /dev/ttyACM0 I see data from the GPS device. If I run the following it is throwing errors:

```
pi@pibuild:~ $ systemctl status gpsd
● gpsd.service - GPS (Global Positioning System) Daemon
   Loaded: loaded (/lib/systemd/system/gpsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-10-29 17:27:57 CDT; 18min ago
  Process: 515 ExecStart=/usr/sbin/gpsd $GPSD_OPTIONS $DEVICES (code=exited, status=0/SUCCESS)
 Main PID: 531 (gpsd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/gpsd.service
           └─531 /usr/sbin/gpsd -n -b /dev/ttyACM0

Oct 29 17:27:57 pibuild systemd[1]: Starting GPS (Global Positioning System) Daemon...
Oct 29 17:27:57 pibuild systemd[1]: Started GPS (Global Positioning System) Daemon.
Oct 29 17:39:36 pibuild gpsd[531]: gpsd:ERROR: SER: device open of /dev/ttyACM0 failed: No such file or directory - retrying read-only
Oct 29 17:39:36 pibuild gpsd[531]: gpsd:ERROR: SER: read-only device open of /dev/ttyACM0 failed: No such file or directory
Oct 29 17:39:36 pibuild gpsd[531]: gpsd:ERROR: /dev/ttyACM0: device activation failed.
Oct 29 17:39:36 pibuild gpsd[531]: gpsd:ERROR: /dev/ttyACM0: activation failed, freeing device
```

**Comment by km4ack** [comment]
Follow this video and it should get it going. https://youtu.be/YIIC-iT6H-s

**Comment by andjones132** [comment]
Thank you, Sir. Your Awesome. That fixed it. Closing the issue and will use KM4ACK@groups.io in the future.

73,
Andrew/K9ACJ
