### ISSUE TITLE
PI-update issue "Missing xterm no such file or katalog"

### ISSUE THREAD

**Issue by OZ1DAE** [km4ack/pi-build#170]
Hi I have now installed PI-Build several times and on several different SD cards. everything works fine. But when I want to use Build-a-pi from the menu to update the build I get this error message: Missing xterm no such file or katalog.

what am I missing I hope I am in the right place for this issue

Best regards  Max OZ1DAE

**Comment by km4ack** [comment]
Check out this issue for the fix https://github.com/km4ack/pi-build/issues/34

**Comment by OZ1DAE** [comment]
Thanks Jason
Vy 73 de OZ1DAE, Max
Med venlig hilsen Max Hansen Ølsted 

    Den onsdag den 11. november 2020 23.07.52 CET skrev KM4ACK <notifications@github.com>:  
 
 


Check out this issue for the fix #34
