### ISSUE TITLE
Script Not Found

### ISSUE THREAD

**Issue by N6UG** [km4ack/pi-build#172]
Had everything running great, GPS, FLRIG,WSJT-X, etc....

Today I boot and connect BUT when I go to Preferences -> Build-A-Pi (to check on versions.)

I get this: "Invalid desktop entry file: '/usr/share/applications/build-a-pi.desktop'"

Please don't tell me to reinstall everything.

Help?

DE N6UG

**Comment by km4ack** [comment]
From the command line run these command:
`cd
rm -rf  pi-build
git clone https://github.com/km4ack/pi-build.git`

And try the shortcut from the menu again.
