### ISSUE TITLE
Loss of GPS position - Possible Fix

### ISSUE THREAD

**Issue by drepamig** [km4ack/pi-build#173]
First off, **thank you** for your effort in making this script!

I've been using this steadily for a week or so and have noticed that my GPS kept losing its fix even if I never moved its location. I followed the tutorial in the youtube video to fix Conky (that fixed the fail to launch on boot), but I'd still keep losing the fix. I ran `gpsmon` and `cgps -s` and saw plenty of data from the GPS dongle, but it would never get a fix. After more trial and error over a few days, I stumbled on [this post in the raspberrypi.org forums](https://www.raspberrypi.org/forums/viewtopic.php?t=180348)

Long story short, I was noticing some of the same behavior as the original poster. It was concluded in the post that the serial console was still active and interfering with the GPS signal. I ran these commands:

`# Universal command should work on all Pi with modern Raspbian Jessie`

`$ sudo systemctl stop serial-getty@serial0.service`
`$ sudo systemctl disable serial-getty@serial0.service`

and then in /boot/cmdline.txt, I commented out the only line in there like so:

`# console=serial0,115200 console=tty1 root=PARTUUID=59978275-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles`

I then rebooted and (so far) GPS has been rock solid.

**Comment by FJRPilot** [comment]
> First off, **thank you** for your effort in making this script!
> 
> I've been using this steadily for a week or so and have noticed that my GPS kept losing its fix even if I never moved its location. I followed the tutorial in the youtube video to fix Conky (that fixed the fail to launch on boot), but I'd still keep losing the fix. I ran `gpsmon` and `cgps -s` and saw plenty of data from the GPS dongle, but it would never get a fix. After more trial and error over a few days, I stumbled on [this post in the raspberrypi.org forums](https://www.raspberrypi.org/forums/viewtopic.php?t=180348)
> 
> Long story short, I was noticing some of the same behavior as the original poster. It was concluded in the post that the serial console was still active and interfering with the GPS signal. I ran these commands:
> 
> `# Universal command should work on all Pi with modern Raspbian Jessie $ sudo systemctl stop serial-getty@serial0.service $ sudo systemctl disable serial-getty@serial0.service`
> 
> and then in /boot/cmdline.txt, I commented out the only line in there like so:
> 
> `# console=serial0,115200 console=tty1 root=PARTUUID=59978275-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles`
> 
> I then rebooted and (so far) GPS has been rock solid.

I tried this fix a week ago and my GPS has now been solid as well...   Thanks for this info!
