### ISSUE TITLE
Build-A-PI update does not work

### ISSUE THREAD

**Issue by jerseyj** [km4ack/pi-build#179]
The splash screen pops up with text that ends with "Ready when you are" but there are no buttons on the screen. A cmd window is open in the background that is blank. Hitting the enter key closes the splash screen and cmd window. Running from a cmd window closes the splash screen. It appears that no actual actions are taking place. There is no indication if there are no updates to be made or anything else.

![IMG_4788](https://user-images.githubusercontent.com/28815641/100257586-1306db80-2f14-11eb-921c-f729489b0bd5.jpeg)

**Comment by km4ack** [comment]
Looks like it is running off of the bottom of teh screen. Try moving the window up or try a higher resolution and you will see the buttons.

**Comment by jerseyj** [comment]
Thank you, duh! I should have figured that one out easily!

I did have another quesiton…when I ran the update in the command window I saw it checking a number of applications, then in the pop up window I was presented with choices of things that I could check off to install/update. Is that supposed to happen ? I thought it would just check the items installed for updates ?

Thanks again for your help,
Jerry
KB2GCG
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"Those who would give up essential liberty to purchase a little temporary safety, deserve neither liberty nor safety." - Ben Franklin

It's also true that those who would give up privacy for security are likely to end up with neither. 
It's not the years in your life that count, but the life in your years"

"Change is Inevitable, Growth is Optional"

"Without continual growth and progress, such words as improvement,

 achievement and success have no meaning." - Benjamin Franklin
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by km4ack** [comment]
It gives you the option of what you want to update. If for some reason you don't want the latest version, don't put a check by that app. This also gives you the option of installing an app that you may have passed on during the initial build.

**Comment by jerseyj** [comment]
Thanks, I’ll put in an enhancement request to have an “update only what I have installed” option.

Jerry
KB2GCG
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"Those who would give up essential liberty to purchase a little temporary safety, deserve neither liberty nor safety." - Ben Franklin

It's also true that those who would give up privacy for security are likely to end up with neither. 
It's not the years in your life that count, but the life in your years"

"Change is Inevitable, Growth is Optional"

"Without continual growth and progress, such words as improvement,

 achievement and success have no meaning." - Benjamin Franklin
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by jerseyj** [comment]
Thank you, that solved the issue.

Jerry


- "Defeat lasts one day, giving up lasts a lifetime."
