### ISSUE TITLE
conkyrc config update for Logbook

### ISSUE THREAD

**Issue by M0TZO** [km4ack/pi-build#189]
Thanks to some helpful people on the Online ARC _(oarc.uk discord)_, I've now got the Logbook part of my Conky screen all lined up and removes the bit in the angle brackets eg _`<callsign:5>`_.  Wasn't sure about how to post in the code bit, but someone else might find useful when editing theirs. Obviously adjust the path as needed.

Please let me know anything to make this neater, I'm happy for feedback too.

**Original**
`${font Arial:bold:size=10}${color White}${tail ~/Documents/mylog.txt 5}`

**Updated**
`${font Arial:bold:size=10}${color White}${exec tail -12 /home/pi/.local/share/WSJT-X/wsjtx_log.adi | sed 's/<[a-zA-Z0-9:_]*//g' | column -t -s ">"}`

Hope this helps

73 Paul M0TZO

**Comment by km4ack** [comment]
Nice! If you would, please post this to the BAP forum as well. Others may find it interesting and want to use it. The forum has more traffic than github. https://groups.io/g/KM4ACK-Pi/topics

73, de KM4ACK
