### ISSUE TITLE
Problems when using VNC to view headless Pi

### ISSUE THREAD

**Issue by simonstrange26** [km4ack/pi-build#191]
Hi Jason,
Love your channel and I've just done a pi-build v3 and am reviewing it for my ham radio youtube channel!  I have caused an issue though, I used NoMachine to VNC into the headless Pi and during the log in stage it said something like "there is no display currently, would you like to create one?"  I said yes since that seemed to be the only choice and now I have 2 systems - the "correct" one when I login with RealVNC and an Openbox version that looks and is set out completely different!  How can I dispose of this "wrong" one?
______________________________________________
![Screenshot from 2020-12-21 22-54-17](https://user-images.githubusercontent.com/57273290/102830131-8ea75b80-43e0-11eb-8fa3-668e70026b89.png)
![Screenshot from 2020-12-21 23-00-59](https://user-images.githubusercontent.com/57273290/102830136-90711f00-43e0-11eb-8a6e-753628b23bf3.png)
Simon M0SYS

**Comment by km4ack** [comment]
Can't say that I have run into this before but I only use RealVNC viewer to log in. It seems to be the most compatible with the VNC viewer and cause the least issues. Maybe try removing No Machine?
