### ISSUE TITLE
SSIDs truncated when selecting WiFi network

### ISSUE THREAD

**Issue by dpsm64** [km4ack/pi-build#195]
The list of networks that comes up when you're first starting build-a-pi seems to truncate SSIDs that have spaces or underscores in them. The attached shows my network as "The" when it's really "The Hack Shack 5G". Not a problem for selecting networks -- I was still able to figure out which one was mine and log in no problem. But it might be something to fix when you get a chance.

Thanks for the script, very nicely done. Donation inbound. 73 DE N7DPM

**Comment by wdbrady** [comment]
I had the same issue, but also have multiple entries with the same "prefix".   I assume this has to do with the fact that I am using an Eero mesh network.  In the attached screen print, my network starts with El and you can see I have multiple entries in addition to my neighbors.   
![Screen Shot 2021-01-08 at 2 39 47 PM](https://user-images.githubusercontent.com/31709512/104057163-a6902500-51bf-11eb-8c7c-7ab620676227.png)

As always, great job on this project!

**Comment by km4ack** [comment]
slated for 3.0.6 release now in beta
