### ISSUE TITLE
Hamlib mix-up

### ISSUE THREAD

**Issue by dafula** [km4ack/pi-build#197]
First Hamlib is installed by compiling from source via pi-build. Then when selecting to install CQRLOG or QSSTV the script installs libhamlib2 and hamlib-dev from the deb package system. Then there are 2 Hamlib - one in /usr and another in /usr/local.
Possible solution for QSSTV is to remove hamlib-dev from the compile dependencies in 
https://github.com/km4ack/pi-build/blob/master/functions/additional.function#L249
and make sure that hamlib is installed from source (the header files will be in /usr/local)
CQRLOG is better to be build from source too, because the Raspbian OS package is rather old.

**Comment by km4ack** [comment]
This issue has been resolved https://github.com/km4ack/pi-build/blob/master/update#L641
