### ISSUE TITLE
Error Invalid entry file

### ISSUE THREAD

**Issue by ricb1** [km4ack/pi-build#205]
I get this error when I click on preference and Build a Pi for update
![20210121_110657](https://user-images.githubusercontent.com/48565314/105378088-73935b80-5bd9-11eb-9346-9640857e396e.jpg)

**Comment by km4ack** [comment]
Please run
ls -l ~/pi-build | grep update

and post the results.

**Comment by ricb1** [comment]
sorry could not wait, I re burned the disk

Rick, kd4dra
