### ISSUE TITLE
Conky redraw incorrect on boot

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#213]
Conky is double drawing on boot with a pi 3 (Buster 02DEC2020) which make it completely unreadable and unusable. I have found the easy fix is to open the Pi Menu. Under the ham radio section, click Conky. This forces Conky to restart and the issue won't return until the next boot. Need to figure out what is causing the issue on boot.

**Comment by KF5KUW** [comment]
Problem also exists with a Pi 4b,w/4Gb RAM.

**Comment by KE0OOS** [comment]
I'm noticing the problem when I power up the BAP.   I'll test further if the problem is on reboot, but it is looking "normal" when I did a reboot this morning.

Running P4b, 4Gb Ram on a 7 inch Pi screen.

**Comment by km4ack** [comment]
as a workaround for the time being, I add this line to crontab
@reboot sleep 30 && export DISPLAY=:0 && /usr/bin/conky

which will restart conky clearing the problem

**Comment by km4ack** [comment]
possible solution on this page - https://askubuntu.com/questions/567737/why-does-conky-superpose-system-data-when-updating-its-output

**Comment by km4ack** [comment]
See [this](https://groups.io/g/KM4ACK-Pi/message/4650) for possible resolution to this issue.
