### ISSUE TITLE
xlog show "needs-update" even after installing.

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#215]
xlog show that an update is available even after selecting it during a BAP update per David Bondy on Patreon. Ref comments on [this post](https://www.patreon.com/posts/install-tool-v3-47747376)

**Comment by DavidNBondy** [comment]
If you need to find this please note that my name is David Bondy not Brody ....

**Comment by km4ack** [comment]
Thanks for catching my typo.

**Comment by km4ack** [comment]
xlog fails to build on pi 3. [issue ticket](https://savannah.nongnu.org/bugs/index.php?60145) submitted to xlog

**Comment by km4ack** [comment]
No response from developer to the [issue ticket](https://savannah.nongnu.org/bugs/index.php?60145) that I created in Feb 2021
