### ISSUE TITLE
Gridtracker not updating

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#223]
not updating to the latest version. see [this post](https://groups.io/g/KM4ACK-Pi/topic/81015410)

**Comment by chrisgaeth** [comment]
Jason,
To fix this you just need to update your Gridtracker GRIDDLL variable to `GRIDDLL=$(curl -s https://gridtracker.org/downloads/ | grep arm | head -1 | sed 's/.*href="//' | sed 's/.gz.*$/.gz/')

**Comment by PA2EJD** [comment]
Jason,
The actual URL for the current version is https://fleetwood.mchambersradio.com/gridtracker/v1.21.0407/GridTracker-1.21.0407-linux-arm.tar.gz Your script resolves the correct tar file name using the url given by chrisgaeth but does not generate the correct url.

I was able to install Gridtracker manually following your lines of code with the new url.

Thanks for the great work on Build a Pi

**Comment by lcgreenwald** [comment]
Jason,
This cleans up the HTML formatting and generates the correct URL:
GRIDDLL=$(curl -s https://gridtracker.org/downloads/ | grep arm | head -1 | sed 's/<p style="padding-left: 80px;"><a href="//' | sed 's/.>GridTracker.*//')

73
Larry - wb0sio

**Comment by lcgreenwald** [comment]
Not sure what corrupted my previous post but I'll try the post again. 
`GRIDDLL=$(curl -s https://gridtracker.org/downloads/ | grep arm | head -1 | sed '/.*href="//' | sed 's/.>GridTracker.*//')

73
Larry - wb0sio

**Comment by dave2492** [comment]
Thanks, Larry.  But I got an error - missing the first sed command.  So, would be:
GRIDDLL=$(curl -s https://gridtracker.org/downloads/ | grep arm | head -1 | sed 's/.*href="//' | sed 's/.>GridTracker.*//')
But then got another error: ERROR 503: Service Temporarily Unavailable.
It appears that cloudflare is blocking access unless you are using a browser (DDOS protection).
See: https://superuser.com/questions/888507/problems-with-wget-to-a-cloudflare-hosted-site-503-service-unavailable
I ended up downloading with the browser and untar'd where build-a-pi expected gridtracker to live.
Dave.

**Comment by km4ack** [comment]
a resolution is in the dev brach of code and will be included in 3.0.8 https://github.com/km4ack/pi-build/commit/e95918681bab5856a7812e450beb5dfc2ae44074

**Comment by km4ack** [comment]
Fixed in 3.0.8 release
