### ISSUE TITLE
Real VNC is almost as bad as Microsoft in RaspianOS

### ISSUE THREAD

**Issue by phoggberg** [km4ack/pi-build#226]
Real VNC requires you to sign into an account before you can use it.  This allows for or at least the potential for tracking.  It's described in this article:  https://www.childs.be/blog/post/remove-real-vnc-from-raspberrypi-pixel-and-install-tightvnc

Fortunately there is a bypass for the problem, that is TightVNCServer.  Additionally instead of using a VNC Client, I use RDP (microsoft remote desktop, not TeamViewer)  It is available for many operating environments including Windows, MacOS, Linux, iOS, Android, etc which allows you to perate on the desktop of the Pi from laptops, tablets, phones, you name it.  I also would suggest adding samba, to transfer files from your home/office computer to the Ham Station computer, and A former Apple Product now in public domain called Bonjour.  
RDP is a much cleaner remote desktop client and more bullet proof than VNC, xrdp is the module you load.  Samba will show files/drives on the Pi on other machines in your local network, thereby making file transfers trivial, and bounjour (avahi) allows you to remotely address your pi by using <hostname>.local instead of an ip address
They can all be added simply as follows:  (Assume the upgrade & update have been done)
    dpkg --get-selections | grep vnc
    sudo apt-get remove realvnc-vnc-server
    sudo apt-get install tightvncserver xrdp avahi-daemon samba samba-common-bin 

these should be simple adds to your script, and the Remote desktop clients are either shipped with windows, or downloadable from apple's mac or ios app store/google play store as Microsoft Remote Desktop

73,
Barry, N0NZ

**Comment by km4ack** [comment]
User are free to add/remove any software they see fit. realvnc doesn't require an account to use with the pi hotspot that most run in the field.
