### ISSUE TITLE
Can't make conky transparent

### ISSUE THREAD

**Issue by wptracy** [km4ack/pi-build#227]
I made conky transparent on the Pi I built but can't make it transparent on the pi-build.

I installed pi-build on Raspberry Pi OS with desktop and recommended software, not on Raspberry Pi OS with desktop or Raspberry Pi OS Lite.

These are the settings in my .conkyrc

    own_window = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

**Comment by km4ack** [comment]
This is probably related to https://github.com/km4ack/pi-build/issues/213
