### ISSUE TITLE
/usr/share/zygrib test should be for a directory 

### ISSUE THREAD

**Issue by roccoq** [km4ack/pi-build#237]
Hi Jason,

I cannot tell you how much I appreciate your build-a-pi scripts. I use nothing but a Pi4 for all my ham radio applications because of what you created. I found a small error on with regards to the zygrib installation check. The update script would not recognize that that zygrib was installed. It seems the test for zygrib was failing each time.

Line 742 the test should be for a directory "-d" rather than a file "-f"
https://github.com/km4ack/pi-build/blob/64c088f6326b8b39eec00bdc80dced78bb53c34c/update#L742

Thanks again and take care!

**Comment by km4ack** [comment]
Glad you are enjoying the build and thanks for the report. I think we figured this out at almost the same time :-) [See 235](https://github.com/km4ack/pi-build/issues/235)
