### ISSUE TITLE
Error message when trying to run Build-a-Pi

### ISSUE THREAD

**Issue by tarjeibr** [km4ack/pi-build#238]
![9B87EB94-AFE2-4184-A3F1-9175CECBAFA1](https://user-images.githubusercontent.com/80761759/111877259-c5225180-89a2-11eb-9968-b1f2acc013ca.jpeg)
Installasjon went well, but afterwards when I run «build-a-pi» and start a scan I unfortunately had disconnected the nettwork cable and I got this error message. After I Connect nettwork and I verifiser that internett worked I still get the same error, Even after reboots. I am a novise with Pi and need help about What to do.

**Comment by 2I0YUM** [comment]
I'm getting the same error too fresh OS build.

**Comment by km4ack** [comment]
reference this [post](https://groups.io/g/KM4ACK-Pi/topic/error_when_running/81497591?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,81497591)
