### ISSUE TITLE
[FEATURE REQUEST] New App Suggestion - Cubic SDR

### ISSUE THREAD

**Issue by darigovresearch** [km4ack/pi-build#239]
[CubicSDR](https://cubicsdr.com/) is an open source software defined radio that is compatible with most low cost RTL USB based SDRs like the Nooelec SDR. It is very helpful to visualise the band space when testing and looking for contacts in the field.

Installation is very simple on the Raspberry Pi with just a one line command:

`sudo apt install cubicsdr`

Was going to make a pull request but bash is not our specialty but happy to do so with some guidance on where to insert what in the relevant sections of the codebase. Probably would fit best to in the 2nd of the 3 menus.

**Comment by km4ack** [comment]
This is simple enough and can be installed from the built in package manager. At this time, there are no plans to include this in BAP.
