### ISSUE TITLE
[BUG] Unable to update software on small tablets

### ISSUE THREAD

**Issue by darigovresearch** [km4ack/pi-build#241]
The menu when working via a VNC on a small tablet device (5 inch Android) appears to have some of the buttons hidden below the viewable space.

I assume the window is just too high and has a button at the bottom that the user needs to click to confirm the update process.

Possible solution would be to resize the window if possible so the smaller buttons. This screen has little to read anyway so would not hinder the use of the update app if it were smaller.

As usual was going to make a pull request but bash is not our specialty but would be happy to do so with some guidance on where to insert what in the relevant sections of the codebase.

**Comment by km4ack** [comment]
duplicate issue. original is #94
