### ISSUE TITLE
Enable CM108/CM119 GPIO PTT for direwolf.

### ISSUE THREAD

**Issue by wb2osz** [km4ack/pi-build#243]
Thank you for including direwolf with Build A Pi.

Please add "sudo apt-get install libudev-dev" to the direwolf build as seen in the README here:  https://github.com/wb2osz/direwolf/blob/master/README.md

This will enable PTT using the GPIO pins of the CM108/CM119 USB audio adapters.

Thanks.

Reference:  https://groups.io/g/direwolf/message/5038

**Comment by km4ack** [comment]
Included in 3.0.8 release
