### ISSUE TITLE
EEPROM on PI 4

### ISSUE THREAD

**Issue by mtkgk** [km4ack/pi-build#244]
Using the Raspbian OS that you have a link to and most of the other OS on a NEW RPI4B  i get No EEPROM bin file found for Versions 2021-03-18 aborting.
I have looked up this ISSUE and not much help on Raspbian or others on how to fix this?

Is this a ISSUE with the Raspberry PI 4B (8meg)??

**Comment by km4ack** [comment]
Reflash the SD card and try again. You might also search "[update eeprom raspberry pi](https://duckduckgo.com/?t=ffcm&q=update+eeprom+raspberry+pi&atb=v159-1&ia=web)"
