### ISSUE TITLE
make[2]: *** [Makefile:370: adif3.o] Error 1   for source /home/pi/xlog-2.0.22/src

### ISSUE THREAD

**Issue by BenHenUnif** [km4ack/pi-build#249]
Hello,

I've got this error when compiling xlog-2.0.22 from sources (pi-build version 3.0.7 on raspberry pi 3b+).
Has anyone any idea how to solve it ?

Thanks and regards, best 73's Ben - ON3ZZT

gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT adif3.o -MD -MP -MF .deps/adif3.Tpo -c -o adif3.o adif3.c
adif3.c: In function ‘adif_qso_append’:
adif3.c:527:4: error: ‘strncpy’ source argument is the same as destination [-Werror=restrict]
    strncpy (qfield, q[fld], qfield_len);  // Save the string from start to space, not including the space.
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

See below the full logfile : 

config.status: creating po/Makefile
Making all in src
make[1] : on entre dans le répertoire « /home/pi/xlog-2.0.22/src »
Making all in logfile
make[2] : on entre dans le répertoire « /home/pi/xlog-2.0.22/src/logfile »
gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT logfile.o -MD -MP -MF .deps/logfile.Tpo -c -o logfile.o logfile.c
mv -f .deps/logfile.Tpo .deps/logfile.Po
gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT flog.o -MD -MP -MF .deps/flog.Tpo -c -o flog.o flog.c
mv -f .deps/flog.Tpo .deps/flog.Po
gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT twlog.o -MD -MP -MF .deps/twlog.Tpo -c -o twlog.o twlog.c
mv -f .deps/twlog.Tpo .deps/twlog.Po
gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT adif3.o -MD -MP -MF .deps/adif3.Tpo -c -o adif3.o adif3.c
adif3.c: In function ‘adif_qso_append’:
adif3.c:527:4: error: ‘strncpy’ source argument is the same as destination [-Werror=restrict]
    strncpy (qfield, q[fld], qfield_len);  // Save the string from start to space, not including the space.
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:370: adif3.o] Error 1
make[2] : on quitte le répertoire « /home/pi/xlog-2.0.22/src/logfile »
make[1]: *** [Makefile:600: all-recursive] Error 1
make[1] : on quitte le répertoire « /home/pi/xlog-2.0.22/src »
make: *** [Makefile:381: all-recursive] Error 1
Making install in src
make[1] : on entre dans le répertoire « /home/pi/xlog-2.0.22/src »
Making install in logfile
make[2] : on entre dans le répertoire « /home/pi/xlog-2.0.22/src/logfile »
gcc -DPACKAGE_NAME=\"xlog\" -DPACKAGE_TARNAME=\"xlog\" -DPACKAGE_VERSION=\"2.0.22\" -DPACKAGE_STRING=\"xlog\ 2.0.22\" -DPACKAGE_BUGREPORT=\"kb1oiq@arrl.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xlog\" -DVERSION=\"2.0.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_IPC_H=1 -DHAVE_SYS_SHM_H=1 -DHAVE_STRPTIME=1 -DHAVE_STRCHR=1 -DHAVE_INDEX=1 -DENABLE_NLS=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -g -O2 -Werror -Wno-deprecated-declarations -Wall -Wno-stringop-truncation -Wno-unused-but-set-variable -MT adif3.o -MD -MP -MF .deps/adif3.Tpo -c -o adif3.o adif3.c
adif3.c: In function ‘adif_qso_append’:
adif3.c:527:4: error: ‘strncpy’ source argument is the same as destination [-Werror=restrict]
    strncpy (qfield, q[fld], qfield_len);  // Save the string from start to space, not including the space.
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:370: adif3.o] Error 1
make[2] : on quitte le répertoire « /home/pi/xlog-2.0.22/src/logfile »
make[1]: *** [Makefile:600: install-recursive] Error 1
make[1] : on quitte le répertoire « /home/pi/xlog-2.0.22/src »
make: *** [Makefile:381: install-recursive] Error 1
IC2 is active
0
pi@raspberrypi:~/pi-build $

**Comment by km4ack** [comment]
Duplicate. See https://github.com/km4ack/pi-build/issues/215
