### ISSUE TITLE
CQRLog does not work

### ISSUE THREAD

**Issue by charudatt** [km4ack/pi-build#25]
CQRlog does not work on Raspberry Pi Stretch on a RPi3B+.

I have to settle to this Hardware as BUSTER + USB on RPi-4 has some issues. I am not able to successfully work my USB Hardware on RPi4+BUSTER.

Gives MSQL error. 

Tried the forums for help but could not find any concrete solution to the problem.

CQRLog works on BUSTER+RPi4

vu2upx

**Comment by km4ack** [comment]
This isn't an issue with the build-a-pi script as it doesn't include support for Stretch. Build-a-pi only supports Buster.
