### ISSUE TITLE
GridTracker upgrade neded

### ISSUE THREAD

**Issue by MikeWills** [km4ack/pi-build#253]
Maybe it's related to the bug I found, but GridTracker has updated. Wil the upgrade script prompt me to update it or how do I go about upgrading it "properly"?

**Comment by PD7RON** [comment]
Yes I have the same problem.
Gridtracker says their is an update. In build-a-pi there is no update needed. What is the way to get it updated.

**Comment by MikeWills** [comment]
#223 I think is the fix. But either I don't know what I'm doing or I edited the wrong spot to test it.

**Comment by darigovresearch** [comment]
@MikeWills & @PD7RON there has been an additional post on the issue https://github.com/km4ack/pi-build/issues/223 which may help to resolve your problem

Could you have a go to see if this is the case?

**Comment by MikeWills** [comment]
I made that change but still doesn't work. If you look at the latest, it's not generating the right URL to detect the latest version. So it's not a fix and I don't have the time nor the bash skills to try to troubleshoot it right now.

**Comment by PD7RON** [comment]
Hello Jason
How and where do I have to use this change in the software for gridtracker.
The update for Girdtracker  is not working. And also the update for flamp and flmsg keeps asking for a needed update.
Further-on I can’t figure-out how to start linbpq. The line ~/linbpq/.linbpq  is not working for me

73 Ron PD7RON

**Comment by MikeWills** [comment]
Same issues, GridTracker is not showing an update for me.

**Comment by km4ack** [comment]
have you updated to BAP 3.0.8?

**Comment by MikeWills** [comment]
Yes, I have. Updated, installed some updates for FLDIGI package, rebooted 3 more times. Nothing.

**Comment by MikeWills** [comment]
Attached some screenshots. 
<img width="625" alt="Screen Shot 2021-08-08 at 8 34 42 PM" src="https://user-images.githubusercontent.com/139305/128652582-733976dd-b245-423c-af2d-5ab7eb196c0a.png">
<img width="588" alt="Screen Shot 2021-08-08 at 8 33 00 PM" src="https://user-images.githubusercontent.com/139305/128652590-e850b33c-8f08-492d-9153-f993573734e9.png">

**Comment by MikeWills** [comment]
One more of the screen. 
<img width="882" alt="Screen Shot 2021-08-08 at 8 43 00 PM" src="https://user-images.githubusercontent.com/139305/128652910-8d5260e3-e4a9-4929-8ca6-66ba22d1a817.png">

**Comment by km4ack** [comment]
Thanks for the report. Reopening this issue. Will try to figure out what the bug is.

**Comment by MikeWills** [comment]
If it helps, I'm on a 4GB Pi4. It shouldn't matter, but I know computers are weird. Let me know if you want some more testing. I am willing to help out if you want to try some things.

**Comment by km4ack** [comment]
Even though BAP says the latest version is installed, what happens if you put a checkmark by it and try to install it anyway? I just installed gridtracker on my test box and 1.21.0620 did install. I did not have a previous version on that pi.

**Comment by MikeWills** [comment]
Okay, there appears to be a script error. I got this during the install.  After rebooting, 1.20 is still installed. 
<img width="529" alt="Screen Shot 2021-08-08 at 9 17 07 PM" src="https://user-images.githubusercontent.com/139305/128654401-6ebaf77a-e34e-44f3-942e-e46af098cf9e.png">

**Comment by PD7RON** [comment]
Hello Mike and Jason
Yes I also have 3.0.8 installed. And Mike I got also a message that the installed version of Gridtracker is still 1.20.
For Flmsg and flamp there is also a message that there is an error.
I am using a raspberry pi 4b with 4G
Testing is ok for me let me know.

73 Ron 
PD7RON

**Comment by PD7RON** [comment]
I forgot to tell that I put a checkmark to install Gridtracker again. But it is still the 1.20 version

73 Ron

**Comment by km4ack** [comment]
can one of you guys run the following command:
`cd ~ && ls`
and post the output. I think I have spotted the issue.

**Comment by MikeWills** [comment]
<img width="511" alt="Screen Shot 2021-08-09 at 8 01 25 AM" src="https://user-images.githubusercontent.com/139305/128710313-65f5c883-fafb-49ab-8645-6f4137faae88.png">

**Comment by km4ack** [comment]
Thanks Mike. First, [backup your pi](https://youtu.be/OcL7Ul-ajz0)....just in case. Next we want to remove the old gridtacker files with
`rm -rf ~/GridTracker`
finally, we want to move the new gridtracker directory to the correct spot.
`mv ~/GridTracker-1.21.0620-linux-arm ~/GridTracker/`
Then open GridTracker from the Pi menu and verify the correct (1.21.0620) is showing as expected.

**Comment by MikeWills** [comment]
That did it! Up and running.

**Comment by km4ack** [comment]
Thanks for confirming. I am going to open another issue and close this one since this problem is a bit different.

**Comment by PD7RON** [comment]
Yes for me also up and running.
Thanks 

73 Ron

**Comment by PD7RON** [comment]
Jason can you tell me how I start linbpq. The line ~/linbpq/.linbpq is not working for me.

73 Ron
PD7RON

**Comment by km4ack** [comment]
Thanks for the report Ron. The file placed on the desktop gives the wrong command. The correct command is
`~/linbpq/./linbpq`
I'll file a new issue ticket so this can be addressed in the future.

**Comment by PD7RON** [comment]
Ok tnx Jason.
I had  already tried 
cd linbpq 
./ linbpq
And saw that it was working.

73 PD7RON
Ron
