### ISSUE TITLE
Add piQtSoundModem and piQtTermTCP

### ISSUE THREAD

**Issue by 5rm** [km4ack/pi-build#256]
As you added BPQ (pilinbpq) those two are important additions. QtSoundModem is better AX25 packet (and more) modem for HF than DW.
https://www.cantab.net/users/john.wiseman/Downloads/Beta/piQtSoundModem
piQtTermTCP is a terminal with TCP and AWG interfaces to work with BPQ and Soundmodem
https://www.cantab.net/users/john.wiseman/Downloads/Beta/piQtTermTCP

Jouko OH5RM

**Comment by km4ack** [comment]
piQtTermTCP was added in version 3.0.5. It is available on the last screen (utilities) during the build. Will consider QtSoundModem. Thanks for the suggestion!

**Comment by km4ack** [comment]
Can you point me to the documentation for QtSoundModem?

**Comment by 5rm** [comment]
Thanks Jason,
PiQtSoundmodem is much handier than dw asit has a gui to set things up and also waterfall which is almost a must on hf. It is a linux port of the famous uz7ho soundmodem.
73
Jouko oh5rm

**Comment by 5rm** [comment]
https://www.cantab.net/users/john.wiseman/Documents/QtSoundModem.html

Terveisin
Jouko Nurma

**Comment by km4ack** [comment]
Thanks!

**Comment by Darrrren** [comment]
This will "level up" the build considerably

**Comment by km4ack** [comment]
Included in 3.0.8 release
