### ISSUE TITLE
Grid Tracker Will Not Download

### ISSUE THREAD

**Issue by NZ1N** [km4ack/pi-build#261]
I had an issue with an update and reflashed my SD with buster. I went and redid Build-a-Pi and everything seems to be working fine except Grid Tracker. I get an error that says "Invalid desktop entry file:' /usr/share/applications/gridtracker.desktop' I have redone everything from the beginning now twice. Same issue. Am I missing something?
Note: I am a watch a video and follow step by step kind of guy so if someone know a fix please pretend I'm 9 years old when explaining the fix.
Thanks,
Will 
NZ1N

**Comment by KN4USA** [comment]
My issue is similar. I did a fresh install and a number of items will not install. Xlog, QSSTV, Gridtracker are all showing "Not Installed"  when I run updater.

**Comment by snwvo7** [comment]
I have exactly the same problem  Xlog, QSSTV, Gridtracker are all showing "Not Installed" when I run updater. and won't install after the second try

**Comment by km4ack** [comment]
Duplicate issue already reported https://github.com/km4ack/pi-build/issues/253 Hope to resolve in 3.0.8.
