### ISSUE TITLE
BaP 3.0.7 does not install GridTracker at all

### ISSUE THREAD

**Issue by KE8RDI** [km4ack/pi-build#265]
Installed BaP 3.0.7 Installed WSJT-X just fine. Went to re-run Pi-Build, selected Grid Tracker. Clicked the 'install selected items' button. Script did something (what - I don't know) then gave me the reboot button. So I rebooted. Clicked Menu, Hamradio, GridTracker and got an error message reading: Invalid desktop entry file: '/usr/share/applications/gridtracker.desktop' 

The file /usr/share/applications/gridtracker.desktop contains the following:

[Desktop Entry]
Name=GridTracker
Comment=GridTracker
GenericName=GridTracker, a WSJT-X Companion
Exec=/home/pi/GridTracker/GridTracker --disable-accelerated-2d-canvas --num-raster-threads=2
Icon=/home/pi/GridTracker/gridtracker.png
Path=/home/pi/GridTracker
Type=Application
Encoding=UTF-8
Terminal=false
Categories=HamRadio

Did the following:
cd /
sudo find / -name "GridTracker*"

Find - Found nothing. Huh?

Re-ran BaP 3.0.7 and it shows GridTracker as not installed. Huh? I guess twice wasn't enough for me so I tried a 3rd time with exactly the same result. Like we used to say back in the old days "Uhh it no workie".

Help please! Got any scripts that install GridTracker from a download or some other source?
Please and thanks,
73 de KE8RDI

**Comment by km4ack** [comment]
duplicate. See https://github.com/km4ack/pi-build/issues/253
