### ISSUE TITLE
Fatal error: libudev.h: No such file or directory 

### ISSUE THREAD

**Issue by WD8BWF** [km4ack/pi-build#268]
Good morning,  Trying to run the updates for Flrig and Fldigi and am getting the message Fatal error: libudev.h: No such file or directory.

**Comment by WD8BWF** [comment]
I had searched for libudev.h and did not find anything. After posting I was browsing and found FLDIGI missing library #263 and saw the fix of sudo apt install libudev-dev. Entered that in the terminal window which solved the install error message.

**Comment by km4ack** [comment]
This issue is resolved in 3.0.8
