### ISSUE TITLE
Restarting build a pi 

### ISSUE THREAD

**Issue by Yaegermeister163** [km4ack/pi-build#275]
I was in the middle of the install.  I checked to install the GPS when I didn't have one.  I got the prompt to plug it in and when I hit cancel the setup application closed.  What is the command to allow me to restart the install?

KJ7ZMO

**Comment by km4ack** [comment]
You can restart with
`cd`
`bash ~/pi-build/build-a-pi`

As this isn't an issue/enhancement for build a pi, please post future tech support questions to the [forum](https://groups.io/g/KM4ACK-Pi/topics).

73, de KM4ACK

**Comment by Yaegermeister163** [comment]
Sorry,

I should know better!

John

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
