### ISSUE TITLE
Headless operation

### ISSUE THREAD

**Issue by K4BQN** [km4ack/pi-build#30]
Jason,

First, thank you for the hard work, your builds are outstanding. One quick note that I just noticed, it seems that with the new PI4 B you cant run headless unless you modify the Config.txt because the PI is looking for an HDMI monitor. Adding the following statement, Adding hdmi_force_hotplug=1 to /boot/config.txt  helps, but the screen definition changes once you connect thru RealVNC. I will appreciate any advice on this issue.

Thank you,

Ed

**Comment by km4ack** [comment]
see this video for the fix. https://youtu.be/Uy6xbC0Hiew

**Comment by K4BQN** [comment]
Thank you for the prompt response.

Ed

**Comment by km4ack** [comment]
Welcome. As far as I know, this isn't something I can correct with the script since the pi is already booted when the user runs the script. The issue has to be resolved by the end user.

**Comment by K4BQN** [comment]
Jason,

Thank you for the great support. I was able to play with the settings, and change some values, and looks very good now. Looking forward to watch the upcoming videos.

Once more thank you, and have a great weekend.

Ed
