### ISSUE TITLE
add hamclock

### ISSUE THREAD

**Issue by pidloop** [km4ack/pi-build#307]
You might want to add HamClock to your collection. Info [here](https://clearskyinstitute.com/ham/HamClock). Thanks.

73, Elwood, WB0OEW

**Comment by km4ack** [comment]
Hamclock can already be installed with Build a Pi. [See this](https://github.com/km4ack/pi-build/blob/master/changelog#L140)

**Comment by pidloop** [comment]
Oops, I only looked at the main list, sorry.

Many thanks.
