### ISSUE TITLE
QUESTION: Adding features after initial build - RIGCTL (HAMLIB)

### ISSUE THREAD

**Issue by KD5QDQ** [km4ack/pi-build#312]
Firstly, this build is AWESOME. BIG FAN. I am new to Pi. I went through a Manual Pat build on my Mac and got frustrated. I bought a Pi4 and tried to manually install again. I got farther, but stuck on rig control. Getting closer, but not all the way there. Your YouTube videos are great. I might have doubled your views all by myself with my rewatching and working alongside you. 

Once I run the Build-a-Pi, my life changed. Woo Hoo. But, I am wiping the Pi in between, so I don't drag a lot of junk with me. 

The first time I ran the build-a-pi, I missed adding the HAMLIB with the RIGCTL. I ran the installer a second time, and it added the RIGCTL, and I can manually run it (thanks to all the manual install experience you gave me on the YouTube videos) and it fully works. But, I can not auto-run Pat without RIGCTL being in the menu. When I manually run RIGCTLD, I see it recognized in the live desktop (BTW, that is really cool too). 

QUESTION: How can I get a button or GUI feature for the RIGCTL added to the PAT MENU?

**Comment by km4ack** [comment]
Rig control is already part of Pat Menu. First open your Pat Menu settings and verify rig control is set to YES. Lower in the settings you will see the rigctl command. By default, rigctl is set to pass the commands through FLRIG (rigctl -m 4) Note: only use rigctl in the settings. The "d" is added by the script for rigctld. Once the settings are correct, rigctl will be started when you choose either "Start ARDOP modem" or "Start Packet Modem".
