### ISSUE TITLE
Initial install - "File Not Found"

### ISSUE THREAD

**Issue by burakd83** [km4ack/pi-build#319]
Upon initial install and using
> git clone https://github.com/km4ack/pi-build.git $HOME/pi-build && bash $HOME/pi-build/build-a-pie
Clone completed with no error. 
Bash stated no file or directory pi-build/build-a-pie.
I found the build-a-pie script is missing the file header for bash - 
> #!/bin/bash
I placed it at the top of the script and after saving the file, it ran with no issue.

-KD2FMW

**Comment by km4ack** [comment]
There is no need for the shebang line since we call the build-a-pi script specifically with bash. You probably got this error if you tried to run "build-a-pie" instead of "build-a-pi"
