### ISSUE TITLE
Gridtracker not installing

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#325]
per [this post](https://groups.io/g/KM4ACK-Pi/message/6128) gridtracker is not installing

**Comment by burakd83** [comment]
Error 503 shows when trying this directly.
wget https://fleetwood.mchambersradio.com/gridtracker/v1.21.0928/GridTracker-1.21.0928-linux-arm32.tar.gz

**Comment by km4ack** [comment]
I have not been able to reproduce this issue. I just downloaded it on my Pi using the wget command.

**Comment by km4ack** [comment]
See this issue https://github.com/km4ack/pi-build/issues/362
