### ISSUE TITLE
hamlib (rigctl) won't install on Bullseye SOLVED

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#338]
libusb-1.0 not available in bullseye. Need to compile from source with:
```
sudo apt install -y libusb-dev libudev-dev
cd ~/Downloads
wget https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.tar.bz2
tar -xvf libusb-1.0.23.tar.bz2
cd libusb-1.0.23/
./configure
make
sudo make install
sudo ldconfig
```
now run hamlib install as before with BAP

**Comment by dafula** [comment]
Hi!
Just to clarify - there is a libusb-1.0 in Bullseye.
You can install the library and the header files via
apt install libusb-1.0-0 libusb-1.0-0-dev
Then the compiling of Hamlib 4.3.1 is without errors.
73! LZ1DAF

**Comment by km4ack** [comment]
> Hi! Just to clarify - there is a libusb-1.0 in Bullseye. You can install the library and the header files via apt install libusb-1.0-0 libusb-1.0-0-dev Then the compiling of Hamlib 4.3.1 is without errors. 73! LZ1DAF

Thanks for the heads up. I overlooked the name change from 1.0 to 1.0-0
