### ISSUE TITLE
Failed to execute child process "xterm" (No such file or directory)

### ISSUE THREAD

**Issue by s9z4dz** [km4ack/pi-build#34]
When I try to executing Pat-Menu in terminal I get the following ... Failed to execute child process "xterm" (No such file or directory)

**Comment by km4ack** [comment]
See this page for resolution https://raspberrypi.stackexchange.com/questions/91428/failed-to-execute-child-process-xterm

**Comment by s9z4dz** [comment]
Problem solve..many thanks ..Blessings

**Comment by km4ack** [comment]
Glad to help. 73, de KM4ACK
