### ISSUE TITLE
JS8Call won't install on Bullseye

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#341]
As a quick workaround, we could install with apt for now as the latest version is in the repository. It would be better to build from source.

**Comment by NullVibes** [comment]
JS8 installed fine on x2 BAPs here.  APT was not used.

**Comment by km4ack** [comment]
> JS8 installed fine on x2 BAPs here. APT was not used.

Did it install with BAP? I got it to compile from source with BAP wasn't working.

**Comment by NullVibes** [comment]
Yes; JS8 installed with BAP on Raspian Bullseye.  x2 RPi's so far.
