### ISSUE TITLE
Add SDR Rsp1a 

### ISSUE THREAD

**Issue by catalinalb** [km4ack/pi-build#36]
Hello Sir,

Adding the SDR-Play RSP1A would be a huge step forward since it's becoming more popular considering its prices /performance.

Sincerely, 
Catalin Alb

**Comment by km4ack** [comment]
The SDR-Play RSP1A is a piece of hardware. Do you have a specific app that you would like included in the build-a-pi?

**Comment by catalinalb** [comment]
Hello,
So I have run the script and install it on the official raspberry image from SDR Play. Worked great.
I also have bought a USB sound card. Please help me to pipe the output from gqrx into WSJT-X. 
In windows, I would have used VB-Audio Cable. 
Is there a way to run the UDP button in gqrx and recieve the audio stream over UDP in WJTX?
Or a way to pipe the audio output to the mic input?

Thank you,
Catalin

**Comment by km4ack** [comment]
Catalin, this is beyond the scope of this project. The build-a-pi script is intended to make it easy for the operator to install apps on the pi. Configuration is left up to the operator. 

this issue has been replaced with https://github.com/km4ack/pi-build/issues/49 which is install of actual SDR software.

**Comment by catalinalb** [comment]
Yes,  I did it the other way around. I have runned the script directly into the raspian image from sdrplay.co.uk and it worked like a charm. Now I run gqrx with RSP1A and wsjt-x through Virtual_Sink (audio).

Thanks,
Catalin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
