### ISSUE TITLE
build-a-pi script fails on Bullseye

### ISSUE THREAD

**Issue by DaniAngel** [km4ack/pi-build#370]
Greetings,

I have cloned your git folder and run the bash build-a-pi script.   It gets as far as making a new window asking for my callsign.  when I enter that, the bash command script stops and it lists the following errors:

ln: failed to create symbolic link '/usr/bin/xterm': File exists
 build-a-pi: line 159: /home/pi/pi-build/intro.txt: Permisson denied
build-a-pi: line 172: /home/pi/pi-build/intro.txt: No such file or directory
rm: cannot remove '/home/pi/pi-build/intro.txt: No such file or directory
build-a-pi: line 226: /home/pi/pi-build/config: Permission denied
build-a-pi: line 231: /home/pi/pi-build/base.txt: Permission denied

Then back to terminal prompt.  Any guidance is greatly appreciated!
Dani
N2FY

**Comment by km4ack** [comment]
We typically see this behavior if you try to run build a pi with sudo. Run it without sudo and it should resolve this issue.
