### ISSUE TITLE
Add CQRlog to update menu

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#380]
It was added back to the first menu build but wasn't added to the update menu. This command should work to install it in the mean time. `source /home/pi/pi-build/functions/additional.function; CQRLOG`

**Comment by capetsch** [comment]
Currently running 64bit Debian GNU/Linux 11 (bullseye) updated as of last night and while the sourcing of the file does attempt to install the cqrlog package there are errors on the install. not sure if its related to 64 bit or not at this point. I do not believe this to be an issue with the build a pi method more of an issue on the CRQLog software install and have opened up a bug report with them (https://www.cqrlog.com/node/3335)

output:

source /home/pi/pi-build/functions/additional.function; CQRLOG
mkdir: cannot create directory ‘/temp’: Permission denied
bash: /config: No such file or directory
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libreadline5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  readline-common

E: Package 'libreadline5' has no installation candidate
fatal: destination path 'cqrlog' already exists and is not an empty directory.
lazbuild --ws=gtk2 --pcp=/tmp/.lazarus src/cqrlog.lpi
make: lazbuild: No such file or directory
make: *** [Makefile:9: cqrlog] Error 127
install -d -v         /usr/bin
install -d -v         /usr/share/cqrlog
install -d -v         /usr/share/cqrlog/ctyfiles
install -d -v         /usr/share/cqrlog/help
install -d -v         /usr/share/cqrlog/help/img
install -d -v         /usr/share/cqrlog/members
install -d -v         /usr/share/cqrlog/xplanet
install -d -v         /usr/share/cqrlog/voice_keyer
install -d -v         /usr/share/cqrlog/zipcodes
install -d -v         /usr/share/cqrlog/images 
install -d -v         /usr/share/cqrlog/images/icon/32x32 
install -d -v         /usr/share/cqrlog/images/icon/64x64
install -d -v         /usr/share/cqrlog/images/icon/128x128 
install -d -v         /usr/share/cqrlog/images/icon/256x256 
install -d -v         /usr/share/pixmaps/cqrlog
install -d -v         /usr/share/icons/cqrlog
install -d -v         /usr/share/applications
install -d -v         /usr/share/appdata
install -d -v         /usr/share/man/man1
install    -v -m 0755 src/cqrlog /usr/bin
install: cannot stat 'src/cqrlog': No such file or directory
make: *** [Makefile:42: install] Error 1

tall] Error 1

CRQLOG Make File lines:
8: cqrlog: src/cqrlog.lpi
9:  	$(CC) --ws=gtk2 --pcp=$(tmpdir)/.lazarus src/cqrlog.lpi
10: 	$(ST) src/cqrlog
11: 	gzip tools/cqrlog.1 -c > tools/cqrlog.1.gz
	
42: install    -v -m 0755 src/cqrlog $(bindir)

sudo apt-get install readline-common
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
readline-common is already the newest version (8.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
