### ISSUE TITLE
Add WARNING to README.md

### ISSUE THREAD

**Issue by CatMeat** [km4ack/pi-build#388]
A warning should be added to README.md to execute this script under the default 'pi' user account. It will cause issues if another account is used. Create any additional users after full installation, if needed.  

FUTURE: Modify the script to accommodate users other than 'pi'.
(I routinely activate a 'k4tfj' account instead of the 'pi' account. Others may wish to do so as well.)
Tj, K4TFJ

**Comment by km4ack** [comment]
This should be a non issue in the upcoming release of Build a Pi as the pi username will not be required.
