### ISSUE TITLE
Add VARA to BAP

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#394]
Once beta is complete for PAT Winlink, VARA needs to be added.

**Comment by km4ack** [comment]
install the bap version by running:
`install_winelink.sh bap`

**Comment by km4ack** [comment]
Now that Pat 0.13.0 has been released and supports VARA, it needs to be included in BAP.

**Comment by lysack** [comment]
Hey Jason,

I was reading a thread on your groups.io and then a video on your Youtube channel about VARA.  I see now that VARA needs to installed by users or we wait for #394 for VARA to be added to BAP :). Looking forward to this update as I now have ARDOP working.

I only have one Pi set up with BAP (need to get a dev BAP) but what is the risk of going with "install_winelink.sh bap" on my PROD version of BAP?

Steve VE7SLZ

**Comment by km4ack** [comment]
> Hey Jason,
> 
> I was reading a thread on your groups.io and then a video on your Youtube channel about VARA. I see now that VARA needs to installed by users or we wait for https://github.com/km4ack/pi-build/issues/394 for VARA to be added to BAP :). Looking forward to this update as I now have ARDOP working.
> 
> I only have one Pi set up with BAP (need to get a dev BAP) but what is the risk of going with "install_winelink.sh bap" on my PROD version of BAP?
> 
> Steve VE7SLZ

I wouldn't recommend using the dev branch of BAP. It is always a work in progress and likely to break something on the system. However, if you want to give VARA a try, it isn't hard to do manually. First, [backup your Pi](https://youtu.be/OcL7Ul-ajz0) and then follow [this video](https://youtu.be/kgdSr5SmV0I) to install VARA. Skip the part that has you install Pat 0.12 and instead use the BAP update tool to upgrade to the latest version of Pat (0.13.1). Keep in mind that a Pi 4 is required to run VARA at this time.

73, de KM4ACK

**Comment by km4ack** [comment]
issue resolved in 3.3.0
