### ISSUE TITLE
Bullseye - Pi4 - FlRig issues

### ISSUE THREAD

**Issue by thufer2002** [km4ack/pi-build#398]
Flrig works for about 2 contacts then locks up in transmit but with no signal driving the xmtr. Can't reboot PI4 must power off/on to reset. Flrig will take a long time to close if "X'ing out of app. As noted by another user Flrig open with 20M selected, also the apps location on the desktop is not remembered and always starts at the same position no mater what I do.

My setup:
Pi4 with Flirc case, UBlock GPS, IC-705 Rig

**Comment by km4ack** [comment]
I could be wrong but this sounds more like an RFI issue than an FLRIG issue. I have the latest version of FLRIG running with my 705 without any issues. Try shortening the USB cable between the Pi and the 705 and adding a ferrite bead or two. 

Another test is to reduce to power of the 705 to 1/2 watt and see if the same issue occurs. If not, it is almost certainly RFI getting into the Pi.

**Comment by thufer2002** [comment]
Some suggestions for ferrite beads? Amazon link? I’ll try it.

 

Though the same length of cable and a PI Zero w2 (Non Bullseye) works just fine. Both pi’s built within last 3 days

 

From: KM4ACK ***@***.***>
Reply-To: km4ack/pi-build ***@***.***>
Date: Sunday, April 10, 2022 at 5:02 PM
To: km4ack/pi-build ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [km4ack/pi-build] Bullseye - Pi4 - FlRig issues (Issue #398)

 

I could be wrong but this sounds more like an RFI issue than an FLRIG issue. I have the latest version of FLRIG running with my 705 without any issues. Try shortening the USB cable between the Pi and the 705 and adding a ferrite bead or two.

Another test is to reduce to power of the 705 to 1/2 watt and see if the same issue occurs. If not, it is almost certainly RFI getting into the Pi.
