### ISSUE TITLE
PAT CATALOG - Weather/GRIB requests missing lat/lon

### ISSUE THREAD

**Issue by rolf-tx** [km4ack/pi-build#399]
When PAT catalog creates a weather requests it appears the lat/long is not set.
I manually specified grid square in PAT menu,  have a GPS but is not locked so no position available from it.

**Comment by km4ack** [comment]
Pat catalog "GPS Weather" pulls the location data from the GPS. If you don't have a lock, you won't be able to use this feature. Try using the city weather instead.
