### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Murzim2** [km4ack/pi-build#41]
After the reboot at the end of the first part of the build a pi script I get the following message in the terminal window. 
(yad:1038): dbind-WARNING **: 16:09:56.555: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
The second tick box menu appears and the install appears to complete ok.
Is this a problem and Is this something that need to be fixed.
Running the latest version on Buster on a Raspberry pi 4

**Comment by km4ack** [comment]
This has been addressed in the FAQ https://app.simplenote.com/publish/wY3zjT
