### ISSUE TITLE
piardopc hangs after transmit

### ISSUE THREAD

**Issue by cskinner74** [km4ack/pi-build#410]
Not sure if this should be raised here or downstream with the piardop team (not sure who maintains that).

I've encountered an issue using Pat Menu with an IC-7100 where I can start the ARDOP modem, connect to the radio with flrig, and the audio settings are correct. The ARDOP GUI that opens shows the waterfall, and I when I attempt to connect to the station, my radio keys, and I can hear the audio being transmitted through the rig's monitor mode, as well as see the power meter, so that part's working fine.

The issue being, after it's done sending, the radio stays in transmit mode and the ARDOP modem has to be killed with -9.

I see this is an issue that's been had by other people as well (https://groups.io/g/bpq32/topic/88545355#34236), and there's a reference to a fix, but it looks like that was provided privately and has not been added to the piardop code.

Any thoughts?

**Comment by km4ack** [comment]
Thanks for the report. This issue has been noted and [there's a fix posted](https://groups.io/g/KM4ACK-Pi/topic/ardop_piardopc_locks_up/90175417?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,90175417,previd%3D9223372036854775807,nextid%3D1654748407848405157&previd=9223372036854775807&nextid=1654748407848405157). As soon as John's test code becomes stable code, I'll get this implemented into BAP.
