### ISSUE TITLE
FEATURE REQUEST: support for DRAWS hat onboard GPS, Soundcard, and RTC

### ISSUE THREAD

**Issue by KJ7RNS** [km4ack/pi-build#412]
Hello, it would be extremely helpful if build-a-pi had built in support for the built in GPS, soundcard, and RTC of the DRAWs hat. I was previously running build-a-pi and a DRAWs hat successfully on buster which required modification of several config files and was quite difficult for me to figure out given limited documentation. If build-a-pi could automatically adjust these files, install the necessary drivers, and configure the various installed ham radio apps it would likely make Build-a-pi much more popular among owners of the DRAWs hat. I have a buster image that was configured with build-a-pi but then modified to work with DRAWs GPS & soundcard, let me know if any of the config files would be helpful as examples.
 
Respectfully Kyle Horne, KJ7RNS

**Comment by km4ack** [comment]
There are no plans at this time to support the DRAWS hat as they maintain their own image.

**Comment by Festerstoybox** [comment]
I have just got the Uputronics Raspberry Pi GPS HAT with RTC for this build-a-pi project, havent recieved it yet but hopefully there may be some support out there for getting it running, if not maybe something like mantioned above so it works with the build (if it doesnt work initially), thanks.

**Comment by SpudGunMan** [comment]
> I have just got the Uputronics Raspberry Pi GPS HAT with RTC for this build-a-pi project, havent recieved it yet but hopefully there may be some support out there for getting it running, if not maybe something like mantioned above so it works with the build (if it doesnt work initially), thanks.

https://www.tomvoboril.com/2021/06/gps-and-raspberry-pi-stratum-1-server.html

**Comment by SpudGunMan** [comment]
Put it all on one, nothing wacky here it's a serial gps via gpio

**Comment by Festerstoybox** [comment]
> > I have just got the Uputronics Raspberry Pi GPS HAT with RTC for this build-a-pi project, havent recieved it yet but hopefully there may be some support out there for getting it running, if not maybe something like mantioned above so it works with the build (if it doesn't work initially), thanks.
> 
> https://www.tomvoboril.com/2021/06/gps-and-raspberry-pi-stratum-1-server.html

hey thanks for this link it worked a treat for a while until i decided to upgrade to the latest build. i found this thread where i first got the link but for some reason it doesn't work anymore, any chance someone got the info for install? maybe a new link? thanks in advance for any help i get.
