### ISSUE TITLE
pi3 vara message for memory

### ISSUE THREAD

**Issue by SpudGunMan** [km4ack/pi-build#448]
the vara memory message pops up every time even when not selected

**Comment by km4ack** [comment]
are you testing this on a Pi 4 or the Pi Desktop OS?

**Comment by SpudGunMan** [comment]
This is test and happens every script run on pi3 hardware (elsewhere has memory I assume so no pop up)

**Comment by km4ack** [comment]
ok. i'll take a look

**Comment by SpudGunMan** [comment]
issue resolved
