### ISSUE TITLE
fldigi build on i86

### ISSUE THREAD

**Issue by SpudGunMan** [km4ack/pi-build#453]
I want to leave this here if its handy later? if not close it 

https://github.com/SpudGunMan/pi-build/tree/flrig

**Comment by SpudGunMan** [comment]
the exact error is:
 build will fail for a FLTK package issue 

that appears to be resolved by installing flak-dev 1.1 and 1.3 with &&

I did test this on i386 and pi4 ARM it worked (haven't tested on pi3 yet)

**Comment by km4ack** [comment]
adding the documentation tag so it's easy to find in the future and closing this as it doesn't pertain specifically to the Pi builds.
