### ISSUE TITLE
pi-build command failed on newly flashed SD Card

### ISSUE THREAD

**Issue by KB3RKM** [km4ack/pi-build#46]
Ran the pi-build command from version 2 on a 64 Gb SD Card that I had flashed NOOBS earlier today with Raspberry Pi Imager.  When the script started to execute I thought I saw a couple of errors scroll by, after a short time, the script paused for a response to the question 'Build FL suite from source? y/n.
I responded 'y' to the question.  At this point the following error message was displayed and the script exited:
/home/pi/pi-build/build-a-pi: line 121: /home/pi/pi-build/appchoices: Permission denied
What do I need to do to work around this?
Ed
KB3RKM

**Comment by km4ack** [comment]
Please see the FAQ for resolution. https://tiny.cc/km4ack-faq
