### ISSUE TITLE
Goes to hotspot if more than 2 in wpa_supplicant

### ISSUE THREAD

**Issue by wb8erj** [km4ack/pi-build#48]
Hello,

Thanks for all your work. I have 3 SSID's in my wpa_supplicant file. When I am at the 3rd location it won't recognize the wifi and goes into the hotspot mode.

When I move the 3rd wifi in the file to the first, then it connects just fine.

**Comment by km4ack** [comment]
Hey Matt,

I tested this today and could not reproduce the issue here. Below is my wpa_supplicant file where only the last entry is correct. It attached first time to the entry even though it was the only the last one that was correct. 


ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
	ssid="KM4ACK-891a"
	psk="PASSWORD"
	key_mgmt=WPA-PSK
}

network={
        ssid="KM4ACK-891a"
        psk="PASSWORD"
        key_mgmt=WPA-PSK
}

network={
        ssid="KM4ACK-891"
        psk="PASSWORD"
        key_mgmt=WPA-PSK
}

73, de KM4ACK

**Comment by wb8erj** [comment]
Jason thanks for taking the time to look at this.

I will look into it further on my end. As an FYI, all of the routers
involved that I am trying to connect to use the DD-WRT firmware. I am
guessing there is some sort of timing issue here. So I have changed a
couple parameters and will test more on my end.

I will keep you posted if I find anything, just in case others run into
this.

Again thank for your time on this great bit of developing and your time
into my issue.

      -- Mike WB8ERJ

**Comment by wb8erj** [comment]
Jason, I think I found something. What tipped me off was when I ran your
add-wifi script. When I scanned for networks it found mine sorta.

Here is the deal, my SSID is "CIA MONITORING VAN" Your script returns just
"CIA" The problem appears to be with the spaces in the SSID, which probably
screws up a bunch of stuff!

So I changed my SSID to ItsMe and problem solved!

So I wonder if others with a space in their SSID also have this problem?

Again thanks for your work!

      -- Mike WB8ERJ

**Comment by km4ack** [comment]
Thanks for the report. I have marked this issue as documentation for others here on github and added this to my FAQ https://tiny.cc/km4ack-faq under the hotspot section.

**Comment by wb8erj** [comment]
One more thing, if there are any SSID's that have a space in the wpa_supplicant file it won't even connect to one that has no space. In other words, all SSID's in the file can't have a space in them.
-------- Original message --------From: KM4ACK <notifications@github.com> Date: 3/26/20  11:29 PM  (GMT-05:00) To: km4ack/pi-build <pi-build@noreply.github.com> Cc: Mike Thompson <wb8erj@gmail.com>, Author <author@noreply.github.com> Subject: Re: [km4ack/pi-build] Goes to hotspot if more than 2 in wpa_supplicant (#48) 
Thanks for the report. I have marked this issue as documentation for others here on github and added this to my FAQ https://tiny.cc/km4ack-faq under the hotspot section.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/km4ack/pi-build/issues/48#issuecomment-604796079",
"url": "https://github.com/km4ack/pi-build/issues/48#issuecomment-604796079",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
