### ISSUE TITLE
issue with boot/config settings

### ISSUE THREAD

**Issue by SpudGunMan** [km4ack/pi-build#485]
https://github.com/km4ack/pi-build/blob/b759058bf480874124aa5e4e53977978b11a3ba8/build-a-pi#L523

should be 

```
        sudo sed -i 's/#hdmi_force_hotplug=1/hdmi_force_hotplug=1/' /boot/config.txt
        sudo sed -i 's/dtoverlay=vc4-kms-v3d/#dtoverlay=vc4-kms-v3d/' /boot/config.txt
        sudo sed -i 's/max_framebuffers=2/#max_framebuffers=2/' /boot/config.txt
```

**Comment by km4ack** [comment]
This isn't appropriate for every build. This is really only needed if the end user is using VNC to access the Pi. Maybe a small helper script the user could run if they are using VNC? Thinking out loud here.
