### ISSUE TITLE
When trying to install on newly flashed Raspberry Pi 4, Github is requesing a username/password.

### ISSUE THREAD

**Issue by guyactual** [km4ack/pi-build#507]
Flashed Raspi device.
Completed the initial setup steps for new OS
rebooted
opened the terminal
ran the following command:
$  git clone https://github.com/km4ack/pi-build.git \
  $HOME/pi-build && bash $HOME/pi-build/build-a-pi

Requested for the following:
Username for https://github.com:
Password for https://github.com:

regardless of what I use, i receive the following error:
Remote: Support for password authentication was removed on August 13, 2021.
Remote: Please see https://docs.ithub.com/en/get-started/get-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication. 

The URL above doesn't go to an actual page. 
Could use some help.

**Comment by km4ack** [comment]
The following two lines are **one** command. Enter both at the same time in terminal.

```
 git clone https://github.com/km4ack/pi-build.git \
  $HOME/pi-build && bash $HOME/pi-build/build-a-pi
```
