### ISSUE TITLE
Pi-Build v2 Install issue

### ISSUE THREAD

**Issue by kb1tji** [km4ack/pi-build#51]
Hello - I took a Pi 4B 2GB mem, installed Buster 4.19 and then ran Pi-Build v2 with instructions from the Video. Took as long as expected, with a long udate/upgrade before build start. I left it unattended and next day I see Pi booted and Pi-Menu Icon, but no Conky, no stop waiting for next menu for secondary install selection. A manual reboot, same results, so not sure what's loaded or what happened. Is there a install log file that will show me what happened on-screen? How to debug? What is xlog and will it help?

Thanks,
Jeff Marden/N1JCM (formally KB1TJI)

**Comment by km4ack** [comment]
Jeff,

Not sure why the second menu didn't open after the reboot. Assuming
everything from the first part of the build installed ok, you should be
able to pick up from where it stopped. From the command line, do the
following:

cd pi-build
bash addon-build-a-pi

The second menu should appear and allow you to continue with the build.

73, de KM4ACK
