### ISSUE TITLE
Script hangs at "Installing VARA FM"

### ISSUE THREAD

**Issue by n2kto** [km4ack/pi-build#516]
Everything was going well untill script tried to install VARA FM.
![Script hang Vara FM Capture](https://github.com/km4ack/pi-build/assets/30575093/49509a82-4908-4e28-8861-8a087a909f2d)

RPI 4
128g sd card
ethernet connected
Ublox GPS in USB2 port

Thanks to all for any help
Dave N2KTO

**Comment by km4ack** [comment]
See this post - https://groups.io/g/KM4ACK-Pi/topic/install_failure/99597785?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,99597785,previd%3D9223372036854775807,nextid%3D1686231809749157223&previd=9223372036854775807&nextid=1686231809749157223
