### ISSUE TITLE
new install of build a pi and it wont install wsjtx ???

### ISSUE THREAD

**Issue by Racerx07** [km4ack/pi-build#525]

**Comment by Racerx07** [comment]
(yad:8616): Gdk-CRITICAL **: 19:36:09.018: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

i get this on my screen when trying to use up-date tool

**Comment by km4ack** [comment]
BAP has been replaced with 73Linux. https://github.com/km4ack/73Linux
