### ISSUE TITLE
Permission denied on build

### ISSUE THREAD

**Issue by ethrane0** [km4ack/pi-build#54]
Did this:
sudo  git clone https://github.com/km4ack/pi-build.git $HOME/pi-build && bash $HOME/pi-build/build-a-pi

Got this:
/home/pi/pi-build/build-a-pi: line 121: /home/pi/pi-build/appchoices: Permission denied

Attempted a couple of times on a new Buster install.  Should be plug and play.  Also get an early error about permission denied on setting the callsign.
Thanks

**Comment by km4ack** [comment]
run the git clone command without sudo 
git clone https://github.com/km4ack/pi-build.git $HOME/pi-build && bash $HOME/pi-build/build-a-pi
