### ISSUE TITLE
Script failed, not sure how to run again from scratch

### ISSUE THREAD

**Issue by mac03579** [km4ack/pi-build#57]
Brand new pi, installed Buster, ran script. Seemed to be going okay - got call sign question, got hotspot questions, got winlink questions, but as I let it do its thing, the screen went black and nothing happened. I thought I might've missed an auto reboot notice, but it didn't reboot. Left it to its own devices for 15 min, but nothing happened. I forced a reboot (hard reboot via power cycle). Desktop clearly didn't have all the things that come from installing the bits your script does, so I tried to re-run the script, but it gave me a fatal error. So I tried the update script, and it is showing that FLDIGI, FLRIG, FLAMP, FLMSG, FLNET, Chirp, Direwold, Pat Menu, GARIM, and Grid Tracker are not installed. I had ticked all the boxes (yes, I have an RTC installed on the Pi). Not quite sure what to do. I fully own being inexperienced on linux. Thanks, AA1AZ (Christy)

**Comment by km4ack** [comment]
Probably best to start completely over. Reflash the card with Buster and try again. Keep in mind that on a Pi 3 it will take 3-4 hours for everything to install. Longer if you have a slower internet connection. It may appear hung on the FLDIGI build. This one portion of the script can take over 30 minutes. 73, de KM4ACK
