### ISSUE TITLE
Prob with Desktop Entry for JS8 Utils in last Build a Pi Script

### ISSUE THREAD

**Issue by sanityassass1n** [km4ack/pi-build#59]
The path in the desktop entry/shortcut for js8utils in the current build-a-pi script is missing a directory.  Only went to the bin directory level. Should be: /home/pi/bin/JS8CallUtilities_V2/JS8CallUtils_v2.py but instead was /home/pi/bin/JS8CallUtils_v2.py.

**Comment by km4ack** [comment]
Great catch!! Thank you. Script updated. 73, de KM4ACK
