### ISSUE TITLE
pull hamlib from github, not sourceforge

### ISSUE THREAD

**Issue by pleasantone** [km4ack/pi-build#64]
Hamlib is now being maintained on github, if you want to stay current, that's the place...
https://hamlib.github.io for more info.

**Comment by km4ack** [comment]
Thanks for the heads up. 73, de KM4ACK

**Comment by SpudGunMan** [comment]
```
        rm -rf Hamlib
        git clone https://github.com/Hamlib/Hamlib
        cd Hamlib
        ./bootstrap
```
this shims over source forge
