### ISSUE TITLE
Pi-build problem

### ISSUE THREAD

**Issue by 2E0WHN** [km4ack/pi-build#68]
Decided to get your build on to my Pi. 

Everything went well. Placed my call in the required area and it went off doing what it needed to do. Then came the option for build. So I pressed y and it came up with this:

Decision time......
The FLDIGI suite can be built from source or downloaded from the 
repository. Building from source will give you the very latest and 
greatest FLDIGI suite. It will also add roughly an hour to the 
build time of this script. If you choose to build from 
source, many of FLDIGI tools will be installed. The 
tools this script includes is FLRIG, FLDIGI, FLARQ, FLMSG, FLAMP.

Build FL suite from source? y/n y
/home/pi/pi-build/build-a-pi: line 121: /home/pi/pi-build/appchoices: Permission denied

So I tried again t osee if it would restart from the beginning:

git clone https://github.com/km4ack/pi-build.git $HOME/pi-build && bash $HOME/pi-build/build-a-pi
fatal: destination path '/home/pi/pi-build' already exists and is not an empty directory.

This is on a new SD card with the latest version of Buster. All dependencies are up to date also. Any ideas what has happened?

**Comment by km4ack** [comment]
From terminal run
rm -rf ~/pi-build
and then
git clone https://github.com/km4ack/pi-build.git $HOME/pi-build && bash $HOME/pi-build/build-a-pi

Your user name needs to be pi and do not use sudo with the above commands.

73, de KM4ACK
