### ISSUE TITLE
Minor bug in Call Sign Lookup

### ISSUE THREAD

**Issue by starbasessd** [km4ack/pi-build#77]
Doesn't correctly account for Suffix (Jr/Sr/ etc.) if it exists. Attached screenshot.
![image](https://user-images.githubusercontent.com/20134429/85430064-a2672780-b54d-11ea-8b94-d06f252b18fa.png)

**Comment by km4ack** [comment]
Issue moved to appropriate repository. https://github.com/km4ack/pi-scripts/issues/21
