### ISSUE TITLE
Remove ‘pi’ user install requirement

### ISSUE THREAD

**Issue by JaySheepdog-N0SR** [km4ack/pi-build#81]
Allow installation of BAP using the current logged in user, checking for and disallowing ‘root’.

‘pi’ is a default user, and current security practices dictate that these type of accounts be disabled (or secured and left unused) and individual user accounts be created instead.

**Comment by Taubin** [comment]
I just wanted to add my two cents here, I'd love to be able to run this as another user. I am building a pi to toss in at my local ham club, and do not want the user exposed to the club users to be root for obvious reasons. I'd love to run this as another user, then remove them from the sudoers.

**Comment by km4ack** [comment]
This was implemented in 3.2.4
