### ISSUE TITLE
Conky freezes when gps is plugged in 

### ISSUE THREAD

**Issue by plowboy68** [km4ack/pi-build#82]
All of the information on my conky display freezes shortly after the gps dongle is plugged in. System clock runs normally. Unplug gps, conky starts running normally.

**Comment by Wirezfree** [comment]
Does it freeze when PI is booted with GPS already connected?

**Comment by plowboy68** [comment]
It does not. I changed the “hotplug” setting in gpsd to true at some point and that was causing the problem when the Pi is already running. If the gps is plugged in at boot with hotplug set to false there is no problem.

**Comment by Wirezfree** [comment]
> It does not. I changed the “hotplug” setting in gpsd to true at some point and that was causing the problem when the Pi is already running. If the gps is plugged in at boot with hotplug set to false there is no problem.

O.K... Will have to see if the other actions on GPS enhancements address this

**Comment by km4ack** [comment]
If you are still having this issue, see [this video](https://youtu.be/YIIC-iT6H-s) for the fix.
