### ISSUE TITLE
Use GPS to set WSJTX Grid

### ISSUE THREAD

**Issue by blackwellj** [km4ack/pi-build#84]
I dont know if its possible but could you use the GPS location to set the Maidenhead grid in WSJTX?

**Comment by km4ack** [comment]
WSJTX may have an API like JS8Call that allows for this but I'm not sure. Check the documentation or ask the developer of WSJTX. If they do have an API, an application like M0IAX tools could be created to allow for this function. https://github.com/m0iax/JS8CallUtilities_V2 If someone creates the application, I will be happy to include in build a pi.

73, de KM4ACK

**Comment by blackwellj** [comment]
I wonder if this could be incorporated http://www.kd2iff.com/node/21

**Comment by blackwellj** [comment]
https://github.com/bmo/py-wsjtx/tree/master/samples @km4ack
