### ISSUE TITLE
FLRig Fails to update

### ISSUE THREAD

**Issue by FJRPilot** [km4ack/pi-build#88]
When re-running the Build-a-Pi script, I am told that the version of FLRig that is installed needs an update.  When I select it, the script downloads the update (1.3.50) and then try's to extract the tarball.  Tar exits with the error "Not found in Archive" (see attached)
![Screenshot from 2020-07-05 13-04-23](https://user-images.githubusercontent.com/35666213/86540198-a6396900-bec0-11ea-9b6c-5ef18c086f89.png)

**Comment by km4ack** [comment]
This has been resolved in 3.0.1. To update, run the following from the command line

cd ~/pi-build
git pull

and try to install again. Please let me know success or fail.

73, de KM4ACK
