### ISSUE TITLE
errors during install

### ISSUE THREAD

**Issue by wfinigan99** [km4ack/pi-build#89]
This is the kind of errors I'm getting during install

Get:3 http://mirror.us.leaseweb.net/raspbian/raspbian buster/main armhf jq armhf 1.5+dfsg-2+b1 [59.3 kB]
Err:1 http://mirrors.syringanetworks.net/raspbian/raspbian buster/main armhf libonig5 armhf 6.9.1-1
  Connection failed [IP: 2605:5800:1:1::7 80]
Err:2 http://mirrors.syringanetworks.net/raspbian/raspbian buster/main armhf libjq1 armhf 1.5+dfsg-2+b1
  Connection failed [IP: 2605:5800:1:1::7 80]
Fetched 59.3 kB in 2min 7s (466 B/s)
E: Failed to fetch http://mirrors.syringanetworks.net/raspbian/raspbian/pool/main/libo/libonig/libonig5_6.9.1-1_armhf.deb  Connection failed [IP: 2605:5800:1:1::7 80]
E: Failed to fetch http://mirrors.syringanetworks.net/raspbian/raspbian/pool/main/j/jq/libjq1_1.5+dfsg-2+b1_armhf.deb  Connection failed [IP: 2605:5800:1:1::7 80]
E: Unable to fetch some archives

I've tried all the apt-get update, upgrade, --fixbroken commands I can find on the internet.  

I just don't know what do do next.  Thanks and 73

**Comment by km4ack** [comment]
Please post this to the forum so we can figure out if this is a true bug or an issue with your particular installation. https://groups.io/g/KM4ACK-Pi/topics

73, de KM4ACK
