### ISSUE TITLE
Feature Request: TQSL

### ISSUE THREAD

**Issue by blackwellj** [km4ack/pi-build#93]
Would it be possible to add TQSL for logging to LOTW?

**Comment by km4ack** [comment]
Thanks for the suggestion. I'll look into it and see what I might be able to figure out. 

73, de KM4ACK

**Comment by lcgreenwald** [comment]
Hi Jason,
I installed TQSL with these commands after a successful Build-a-pi v3.0.3 beta install.

sudo apt install -y cmake g++ libexpat1-dev libssl-dev libdb++-dev libcurl4-openssl-dev libwxgtk3.0-dev
git clone https://git.code.sf.net/p/trustedqsl/tqsl trustedqsl-tqsl
cd ~/trustedqsl-tqsl
cmake .
make
sudo make install
sudo cp /home/pi/trustedqsl-tqsl/apps/tqsl.desktop /usr/share/applications/

**Comment by km4ack** [comment]
Thanks @lcgreenwald On the map for 3.0.4 release
